-- =============================================
-- PGVECTOR src FOR SMART GARDEN BOT
-- Vector similarity search queries for AI/ML features
-- =============================================

-- Prerequisites: Ensure pgvector extension is installed
-- CREATE EXTENSION IF NOT EXISTS vector;

-- =============================================
-- 1. PLANT DISEASE SIMILARITY SEARCH
-- =============================================

-- Find similar plant diseases based on image embeddings
-- This query finds the top 5 most similar disease cases to a given plant image

WITH query_embedding AS (
    -- In practice, this would be the embedding of the query image
    -- generated by your ML model (e.g., a 512-dimensional vector)
    SELECT '[0.1, 0.2, 0.3, ..., 0.512]'::vector(512) as embedding
)
SELECT 
    pdd.id,
    pdd.zone_id,
    z.name as zone_name,
    pdd.detected_diseases,
    pdd.confidence_scores,
    pdd.processed_at,
    -- Calculate cosine similarity (1 - cosine distance)
    1 - (e.embedding <=> qe.embedding) as similarity_score
FROM analytics.plant_disease_detections pdd
JOIN analytics.embeddings e ON e.entity_id = pdd.id AND e.entity_type = 'plant_image'
JOIN gardens.zones z ON z.id = pdd.zone_id
CROSS JOIN query_embedding qe
WHERE e.model_name = 'plant_disease_model_v2'
ORDER BY e.embedding <=> qe.embedding  -- Order by cosine distance (ascending)
LIMIT 5;

-- =============================================
-- 2. SEASONAL GROWTH PATTERN ANALYSIS
-- =============================================

-- Find zones with similar growth patterns using sensor data embeddings
-- This helps identify optimal growing conditions and predict outcomes

WITH target_zone_embedding AS (
    SELECT embedding
    FROM analytics.embeddings 
    WHERE entity_type = 'growth_pattern' 
      AND entity_id = '770e8400-e29b-41d4-a716-446655440001' -- Target zone
      AND model_name = 'growth_pattern_model_v1'
    LIMIT 1
)
SELECT 
    e.entity_id as zone_id,
    z.name as zone_name,
    z.plant_type,
    g.name as garden_name,
    u.name as owner_name,
    -- Similarity score
    1 - (e.embedding <=> tze.embedding) as pattern_similarity,
    -- Additional context
    z.metadata->'varieties' as plant_varieties,
    z.metadata->'planting_date' as planting_date
FROM analytics.embeddings e
JOIN gardens.zones z ON z.id = e.entity_id::uuid
JOIN gardens.gardens g ON g.id = z.garden_id
JOIN auth.users u ON u.id = g.user_id
CROSS JOIN target_zone_embedding tze
WHERE e.entity_type = 'growth_pattern'
  AND e.model_name = 'growth_pattern_model_v1'
  AND e.entity_id != '770e8400-e29b-41d4-a716-446655440001' -- Exclude the target zone
ORDER BY e.embedding <=> tze.embedding
LIMIT 10;

-- =============================================
-- 3. WEATHER PATTERN MATCHING
-- =============================================

-- Find historical weather patterns similar to current conditions
-- Useful for predicting optimal watering schedules and plant care

CREATE OR REPLACE FUNCTION find_similar_weather_patterns(
    query_vector vector(512),
    similarity_threshold float DEFAULT 0.7,
    limit_results int DEFAULT 20
)
RETURNS TABLE (
    pattern_date date,
    similarity_score float,
    weather_data jsonb,
    watering_events_count bigint,
    avg_soil_moisture float
) AS $$
BEGIN
    RETURN QUERY
    WITH similar_patterns AS (
        SELECT 
            e.entity_id,
            1 - (e.embedding <=> query_vector) as similarity,
            e.created_at::date as pattern_date
        FROM analytics.embeddings e
        WHERE e.entity_type = 'weather_pattern'
          AND e.model_name = 'weather_pattern_model_v1'
          AND (1 - (e.embedding <=> query_vector)) >= similarity_threshold
        ORDER BY e.embedding <=> query_vector
        LIMIT limit_results
    ),
    pattern_context AS (
        SELECT 
            sp.entity_id,
            sp.similarity,
            sp.pattern_date,
            wd.data as weather_data,
            COUNT(we.id) as watering_count,
            AVG(sr.soil_moisture) as avg_moisture
        FROM similar_patterns sp
        LEFT JOIN sensors.weather_data wd ON wd.id = sp.entity_id::uuid
        LEFT JOIN sensors.watering_events we ON we.started_at::date = sp.pattern_date
        LEFT JOIN sensors.readings sr ON sr.timestamp::date = sp.pattern_date
        GROUP BY sp.entity_id, sp.similarity, sp.pattern_date, wd.data
    )
    SELECT 
        pc.pattern_date,
        pc.similarity::float as similarity_score,
        pc.weather_data,
        pc.watering_count,
        pc.avg_moisture::float
    FROM pattern_context pc
    ORDER BY pc.similarity DESC;
END;
$$ LANGUAGE plpgsql;

-- Example usage of the weather pattern function
SELECT * FROM find_similar_weather_patterns(
    '[0.15, 0.32, 0.18, ...]'::vector(512), -- Current weather pattern embedding
    0.8, -- 80% similarity threshold
    15   -- Return top 15 matches  
);

-- =============================================
-- 4. PLANT RECOMMENDATION SYSTEM
-- =============================================

-- Recommend plants based on similar growing conditions and user preferences
-- This uses embeddings of environmental conditions, soil types, and success rates

WITH user_garden_conditions AS (
    -- Get embedding representing current garden conditions
    SELECT 
        g.id as garden_id,
        e.embedding as conditions_embedding
    FROM gardens.gardens g
    JOIN analytics.embeddings e ON e.entity_id = g.id AND e.entity_type = 'garden_conditions'
    WHERE g.user_id = '550e8400-e29b-41d4-a716-446655440001' -- Target user
      AND e.model_name = 'garden_conditions_model_v1'
    LIMIT 1
),
successful_plant_matches AS (
    -- Find plants that succeeded in similar conditions
    SELECT 
        e.entity_id as plant_variety_id,
        z.plant_type,
        z.metadata->'varieties' as varieties,
        1 - (e.embedding <=> ugc.conditions_embedding) as condition_match,
        -- Success metrics
        AVG(CASE WHEN we.status = 'completed' THEN 1.0 ELSE 0.0 END) as success_rate,
        COUNT(we.id) as total_waterings,
        AVG(sr.soil_moisture) as avg_soil_moisture
    FROM analytics.embeddings e
    JOIN gardens.zones z ON z.id = e.entity_id::uuid
    JOIN sensors.watering_events we ON we.zone_id = z.id
    JOIN sensors.readings sr ON sr.zone_id = z.id
    CROSS JOIN user_garden_conditions ugc
    WHERE e.entity_type = 'plant_success_profile'
      AND e.model_name = 'plant_success_model_v1'
      AND (1 - (e.embedding <=> ugc.conditions_embedding)) > 0.75 -- 75% similarity threshold
    GROUP BY e.entity_id, z.plant_type, z.metadata, e.embedding, ugc.conditions_embedding
    HAVING COUNT(we.id) >= 5 -- At least 5 watering events for reliable data
)
SELECT 
    plant_type,
    varieties,
    condition_match,
    success_rate,
    total_waterings,
    avg_soil_moisture,
    -- Recommendation score combining similarity and success rate
    (condition_match * 0.6 + success_rate * 0.4) as recommendation_score
FROM successful_plant_matches
ORDER BY recommendation_score DESC
LIMIT 10;

-- =============================================
-- 5. ANOMALY DETECTION IN SENSOR DATA
-- =============================================

-- Find unusual sensor reading patterns using vector embeddings
-- This helps identify potential issues with plants or equipment

CREATE OR REPLACE FUNCTION detect_sensor_anomalies(
    zone_id_param uuid,
    lookback_days int DEFAULT 7,
    anomaly_threshold float DEFAULT 0.6
)
RETURNS TABLE (
    timestamp_anomaly timestamp with time zone,
    anomaly_score float,
    sensor_values jsonb,
    similar_normal_patterns text[]
) AS $$
BEGIN
    RETURN QUERY
    WITH recent_readings AS (
        -- Get recent sensor readings for the zone
        SELECT 
            timestamp,
            json_build_object(
                'temperature', temperature,
                'humidity', humidity,
                'soil_moisture', soil_moisture,
                'soil_temperature', soil_temperature,
                'light_intensity', light_intensity
            ) as reading_values
        FROM sensors.readings sr
        WHERE sr.zone_id = zone_id_param
          AND sr.timestamp >= CURRENT_TIMESTAMP - (lookback_days || ' days')::interval
        ORDER BY timestamp DESC
    ),
    reading_embeddings AS (
        -- In practice, these embeddings would be generated by your ML pipeline
        -- This is a simplified example showing the structure
        SELECT 
            rr.timestamp,
            rr.reading_values,
            -- Placeholder: embeddings would be generated from the sensor values
            -- using a trained model that understands normal vs anomalous patterns
            e.embedding
        FROM recent_readings rr
        JOIN analytics.embeddings e ON e.entity_type = 'sensor_reading'
          AND e.created_at::date = rr.timestamp::date
        WHERE e.model_name = 'sensor_anomaly_model_v1'
    ),
    normal_pattern_baseline AS (
        -- Get embeddings representing normal sensor patterns for this zone
        SELECT AVG(e.embedding) as normal_embedding
        FROM analytics.embeddings e
        WHERE e.entity_type = 'normal_sensor_pattern'
          AND e.entity_id = zone_id_param::text
          AND e.model_name = 'sensor_anomaly_model_v1'
    )
    SELECT 
        re.timestamp as timestamp_anomaly,
        (1 - (re.embedding <=> npb.normal_embedding))::float as anomaly_score,
        re.reading_values as sensor_values,
        ARRAY['High soil moisture with low humidity', 'Temperature spike detected']::text[] as similar_normal_patterns
    FROM reading_embeddings re
    CROSS JOIN normal_pattern_baseline npb
    WHERE (1 - (re.embedding <=> npb.normal_embedding)) < anomaly_threshold
    ORDER BY (re.embedding <=> npb.normal_embedding) DESC
    LIMIT 20;
END;
$$ LANGUAGE plpgsql;

-- Example usage
SELECT * FROM detect_sensor_anomalies(
    '770e8400-e29b-41d4-a716-446655440001'::uuid, -- Zone ID
    14, -- Look back 14 days
    0.7  -- Anomaly threshold (70% similarity to normal patterns)
);

-- =============================================
-- 6. OPTIMAL WATERING TIME PREDICTION
-- =============================================

-- Use vector similarity to predict optimal watering times based on 
-- environmental conditions, plant needs, and historical success

WITH current_conditions AS (
    -- Current environmental conditions as embedding
    SELECT 
        e.embedding as conditions_vector,
        sr.zone_id,
        sr.timestamp as current_time
    FROM sensors.readings sr
    JOIN analytics.embeddings e ON e.entity_type = 'environmental_conditions'
      AND e.created_at::date = sr.timestamp::date
    WHERE sr.zone_id = '770e8400-e29b-41d4-a716-446655440001'
      AND e.model_name = 'environmental_model_v1'
    ORDER BY sr.timestamp DESC
    LIMIT 1
),
historical_success_patterns AS (
    -- Find historically successful watering times under similar conditions
    SELECT 
        we.started_at,
        extract(hour from we.started_at) as watering_hour,
        we.actual_duration_minutes,
        we.water_volume_liters,
        we.soil_moisture_before,
        we.soil_moisture_after,
        e.embedding as historical_conditions,
        1 - (e.embedding <=> cc.conditions_vector) as condition_similarity,
        -- Success metrics
        CASE 
            WHEN we.status = 'completed' AND (we.soil_moisture_after - we.soil_moisture_before) > 20 
            THEN 1.0 
            ELSE 0.0 
        END as success_score
    FROM sensors.watering_events we
    JOIN analytics.embeddings e ON e.entity_type = 'environmental_conditions'
      AND e.created_at::date = we.started_at::date
    CROSS JOIN current_conditions cc
    WHERE we.zone_id = cc.zone_id
      AND e.model_name = 'environmental_model_v1'
      AND we.started_at >= CURRENT_TIMESTAMP - INTERVAL '90 days' -- Last 3 months
      AND (1 - (e.embedding <=> cc.conditions_vector)) > 0.8 -- 80% similar conditions
)
SELECT 
    watering_hour,
    COUNT(*) as frequency,
    AVG(success_score) as avg_success_rate,
    AVG(condition_similarity) as avg_condition_match,
    AVG(actual_duration_minutes) as recommended_duration,
    AVG(soil_moisture_after - soil_moisture_before) as avg_moisture_increase,
    -- Overall recommendation score
    (AVG(success_score) * 0.5 + AVG(condition_similarity) * 0.3 + COUNT(*)::float/10 * 0.2) as recommendation_score
FROM historical_success_patterns
GROUP BY watering_hour
HAVING COUNT(*) >= 3 -- At least 3 historical src
ORDER BY recommendation_score DESC
LIMIT 5;

-- =============================================
-- 7. VECTOR INDEX OPTIMIZATION
-- =============================================

-- Create optimized indexes for vector similarity searches
-- These indexes significantly improve query performance

-- HNSW index for fast approximate nearest neighbor search
CREATE INDEX IF NOT EXISTS idx_embeddings_hnsw_cosine 
ON analytics.embeddings 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- IVFFlat index for better recall on smaller datasets
CREATE INDEX IF NOT EXISTS idx_embeddings_ivfflat_cosine 
ON analytics.embeddings 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Partial indexes for specific entity types (better performance)
CREATE INDEX IF NOT EXISTS idx_embeddings_plant_disease_hnsw
ON analytics.embeddings 
USING hnsw (embedding vector_cosine_ops)
WHERE entity_type = 'plant_image';

CREATE INDEX IF NOT EXISTS idx_embeddings_weather_pattern_hnsw
ON analytics.embeddings 
USING hnsw (embedding vector_cosine_ops)
WHERE entity_type = 'weather_pattern';

-- =============================================
-- 8. VECTOR MAINTENANCE AND UTILITIES
-- =============================================

-- Function to calculate embedding statistics
CREATE OR REPLACE FUNCTION embedding_statistics(
    entity_type_param text DEFAULT NULL,
    model_name_param text DEFAULT NULL
)
RETURNS TABLE (
    entity_type text,
    model_name text,
    total_embeddings bigint,
    avg_vector_norm float,
    dimension_count int
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        e.entity_type,
        e.model_name,
        COUNT(*) as total_embeddings,
        AVG(sqrt((e.embedding <#> e.embedding))) as avg_vector_norm,
        vector_dims(e.embedding) as dimension_count
    FROM analytics.embeddings e
    WHERE (entity_type_param IS NULL OR e.entity_type = entity_type_param)
      AND (model_name_param IS NULL OR e.model_name = model_name_param)
    GROUP BY e.entity_type, e.model_name, vector_dims(e.embedding)
    ORDER BY total_embeddings DESC;
END;
$$ LANGUAGE plpgsql;

-- View current embedding statistics
SELECT * FROM embedding_statistics();

-- Function to clean up old embeddings
CREATE OR REPLACE FUNCTION cleanup_old_embeddings(
    days_to_keep int DEFAULT 365,
    dry_run boolean DEFAULT true
)
RETURNS TABLE (
    action text,
    entity_type text,
    model_name text,
    affected_rows bigint
) AS $$
DECLARE
    cleanup_date timestamp with time zone;
    rec record;
    delete_count bigint;
BEGIN
    cleanup_date := CURRENT_TIMESTAMP - (days_to_keep || ' days')::interval;
    
    FOR rec IN 
        SELECT e.entity_type, e.model_name, COUNT(*) as old_count
        FROM analytics.embeddings e
        WHERE e.created_at < cleanup_date
        GROUP BY e.entity_type, e.model_name
    LOOP
        IF dry_run THEN
            RETURN QUERY SELECT 
                'DRY_RUN_DELETE'::text,
                rec.entity_type,
                rec.model_name,
                rec.old_count;
        ELSE
            DELETE FROM analytics.embeddings
            WHERE entity_type = rec.entity_type
              AND model_name = rec.model_name
              AND created_at < cleanup_date;
            
            GET DIAGNOSTICS delete_count = ROW_COUNT;
            
            RETURN QUERY SELECT 
                'DELETED'::text,
                rec.entity_type,
                rec.model_name,
                delete_count;
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Check what would be deleted (dry run)
SELECT * FROM cleanup_old_embeddings(180, true); -- Check 6 months retention

-- =============================================
-- 9. SIMILARITY SEARCH PERFORMANCE TESTING
-- =============================================

-- Function to test vector search performance
CREATE OR REPLACE FUNCTION test_vector_search_performance(
    test_embedding vector(512),
    limit_results int DEFAULT 100
)
RETURNS TABLE (
    search_type text,
    execution_time_ms float,
    results_returned bigint
) AS $$
DECLARE
    start_time timestamp;
    end_time timestamp;
    result_count bigint;
BEGIN
    -- Test 1: Cosine similarity with HNSW index
    start_time := clock_timestamp();
    
    SELECT COUNT(*) INTO result_count
    FROM (
        SELECT e.id
        FROM analytics.embeddings e
        ORDER BY e.embedding <=> test_embedding
        LIMIT limit_results
    ) sub;
    
    end_time := clock_timestamp();
    
    RETURN QUERY SELECT 
        'cosine_hnsw'::text,
        EXTRACT(epoch FROM (end_time - start_time)) * 1000,
        result_count;

    -- Test 2: L2 distance
    start_time := clock_timestamp();
    
    SELECT COUNT(*) INTO result_count
    FROM (
        SELECT e.id
        FROM analytics.embeddings e
        ORDER BY e.embedding <-> test_embedding
        LIMIT limit_results
    ) sub;
    
    end_time := clock_timestamp();
    
    RETURN QUERY SELECT 
        'l2_distance'::text,
        EXTRACT(epoch FROM (end_time - start_time)) * 1000,
        result_count;

    -- Test 3: Inner product
    start_time := clock_timestamp();
    
    SELECT COUNT(*) INTO result_count
    FROM (
        SELECT e.id
        FROM analytics.embeddings e
        ORDER BY e.embedding <#> test_embedding DESC
        LIMIT limit_results
    ) sub;
    
    end_time := clock_timestamp();
    
    RETURN QUERY SELECT 
        'inner_product'::text,
        EXTRACT(epoch FROM (end_time - start_time)) * 1000,
        result_count;
END;
$$ LANGUAGE plpgsql;

-- Example performance test
-- SELECT * FROM test_vector_search_performance('[0.1, 0.2, ...]'::vector(512), 50);

-- =============================================
-- COMPLETION NOTICE
-- =============================================

DO $$
BEGIN
    RAISE NOTICE '==============================================';
    RAISE NOTICE 'PGVECTOR src LOADED SUCCESSFULLY';
    RAISE NOTICE '==============================================';
    RAISE NOTICE 'Available vector search src:';
    RAISE NOTICE '1. Plant disease similarity search';
    RAISE NOTICE '2. Seasonal growth pattern analysis';
    RAISE NOTICE '3. Weather pattern matching';
    RAISE NOTICE '4. Plant recommendation system';
    RAISE NOTICE '5. Sensor anomaly detection';
    RAISE NOTICE '6. Optimal watering time prediction';
    RAISE NOTICE '7. Vector index optimization';
    RAISE NOTICE '8. Maintenance and utility functions';
    RAISE NOTICE '9. Performance testing tools';
    RAISE NOTICE '==============================================';
    RAISE NOTICE 'Note: Embedding vectors shown as placeholders.';
    RAISE NOTICE 'In production, use actual ML model outputs.';
    RAISE NOTICE '==============================================';
END $$;