{{- if .Values.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-garden-bot.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smart-garden-bot.labels.api" . | nindent 4 }}
  {{- with .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    argocd.argoproj.io/sync-wave: "2"
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "smart-garden-bot.selectorLabels.api" . | nindent 4 }}
{{- end }}