---
apiVersion: v1
kind: Namespace
metadata:
  name: smart-garden-bot
  labels:
    app.kubernetes.io/name: smart-garden-bot
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: platform
    app.kubernetes.io/managed-by: argocd
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: smart-garden-bot-system
  labels:
    app.kubernetes.io/name: smart-garden-bot
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: system
    app.kubernetes.io/managed-by: argocd
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: smart-garden-bot-monitoring
  labels:
    app.kubernetes.io/name: smart-garden-bot
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: argocd
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"